#!/bin/sh
# Begin $rc_base/init.d/pris-throttle-d

. /etc/sysconfig/rc
. $rc_functions

BIN_DIR=/home/victor/Apps/throttle-d
LOG_DIR=/mnt/Media/Scratch/throttle-d/logs

case "$1" in
	start)
		boot_mesg "Starting pris-throttle-d..."
		$BIN_DIR/throttle-data-d.pl >> $LOG_DIR/data.log 2>&1 &
		$BIN_DIR/throttle-sgnl-d.pl >> $LOG_DIR/sgnl.log 2>&1 &
		$BIN_DIR/throttle-push-d.sh >> $LOG_DIR/push.log 2>&1 &
		;;

	stop)
		boot_mesg "Stopping pris-throttle-d..."
		killall throttle-sgnl-d.pl
		killall throttle-data-d.pl
		killall throttle-push-d.sh
		killall throttle-push-d.pl
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
