#!/bin/bash

source "/pris/pris-fns.sh"
source "/pris/pris-pkgs.sh"

##############################################################################
## INIT                                                                     ##

write_pid "pris-rebuild-b"

##############################################################################
## MAIN                                                                     ##

cmd "cat > ~/.bash_profile << \"EOF\"
exec env -i HOME=\$HOME TERM=\$TERM PS1='[\h:\w]\n> ' /bin/bash
EOF"
cmd "cat > ~/.bashrc << \"EOF\"
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
PATH=/tools/bin:/bin:/usr/bin
export LFS LC_ALL PATH
EOF"

echo_cmd "source ~/.bash_profile"

# Instead of sourcing the newly-created file, which would put us in a new 
# shell, set env manually.
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
PATH=/tools/bin:/bin:/usr/bin
export LFS LC_ALL PATH

cmd "cd ${MOUNT}/src"

if ! marker_exists "tools-binutils-pass1" ; then
    download_pkg ${BINUTILS_PKG}
    unpack_pkg ${BINUTILS_PKG}
    download_patches ${BINUTILS_PATCH0}
    cmd "cd ${PKG_WORKDIR}"
    cmd "patch -Np1 -i ../${PATCH_FILES[0]}"
    [[ -e ../binutils-build ]] && rm -rf ../binutils-build
    cmd "mkdir -v ../binutils-build"
    cmd "cd ../binutils-build"
    cmd "CC=\"gcc -B/usr/bin/\" ../binutils-2.18/configure \\
    --prefix=/tools --disable-nls --disable-werror"
    cmd "make"
    cmd "make install"
    cmd "make -C ld clean"
    cmd "make -C ld LIB_PATH=/tools/lib"
    cmd "cp -v ld/ld-new /tools/bin"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR} binutils-build"
    place_marker "tools-binutils-pass1"
fi

if ! marker_exists "tools-gcc-pass1" ; then
    download_pkg ${MPFR_PKG}
    download_pkg ${GMP_PKG}
    download_pkg ${GCC_PKG}
    unpack_pkg ${GCC_PKG}
    cmd "cd ${PKG_WORKDIR}"
    get_pkg_file ${MPFR_PKG}
    cmd "tar xvf ../${PKG_FILE}"
    cmd "mv mpfr-2.3.2 mpfr"
    get_pkg_file ${GMP_PKG}
    cmd "tar xvf ../${PKG_FILE}"
    cmd "mv gmp-4.2.4 gmp"
    [[ -e ../gcc-build ]] && rm -rf ../gcc-build
    cmd "mkdir -v ../gcc-build"
    cmd "cd ../gcc-build"
    cmd "CC=\"gcc -B/usr/bin/\" ../gcc-4.3.2/configure --prefix=/tools \\
    --with-local-prefix=/tools --disable-nls --enable-shared --disable-libssp \\
    --enable-languages=c"
    cmd "make"
    cmd "make install"
    cmd "ln -vs libgcc.a \`gcc -print-libgcc-file-name | \\
    sed 's/libgcc/&_eh/'\`"
    cmd "ln -vs gcc /tools/bin/cc"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR} gcc-build"
    place_marker "tools-gcc-pass1"
fi

if ! marker_exists "tools-linux-headers" ; then
    download_pkg ${LINUX_PKG}
    unpack_pkg ${LINUX_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "make mrproper"
    cmd "make headers_check"
    cmd "make INSTALL_HDR_PATH=dest headers_install"
    cmd "cp -rv dest/include/* /tools/include"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-linux-headers"
fi

if ! marker_exists "tools-glibc" ; then
    download_pkg ${GLIBC_PKG}
    unpack_pkg ${GLIBC_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "sed -i 's@/etc/ld.so.preload@/tools/etc/ld.so.preload@' elf/rtld.c"
    [[ -e ../glibc-build ]] && rm -rf ../glibc-build
    cmd "mkdir -v ../glibc-build"
    cmd "cd ../glibc-build"
    cmd 'echo "CFLAGS += -march=i486 -mtune=native" > configparms'
    cmd "../glibc-2.8-20080929/configure --prefix=/tools \\
    --disable-profile --enable-add-ons \\
    --enable-kernel=2.6.0 --with-binutils=/tools/bin \\
    --without-gd --with-headers=/tools/include \\
    --without-selinux"
    cmd "make"
    cmd "mkdir -v /tools/etc"
    cmd "touch /tools/etc/ld.so.conf"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR} glibc-build"
    place_marker "tools-glibc"
fi

if ! marker_exists "tools-adjust" ; then
    cmd "mv -v /tools/bin/{ld,ld-old}"
    cmd "mv -v /tools/\$(gcc -dumpmachine)/bin/{ld,ld-old}"
    cmd "mv -v /tools/bin/{ld-new,ld}"
    cmd "ln -sv /tools/bin/ld /tools/\$(gcc -dumpmachine)/bin/ld"
    cmd "gcc -dumpspecs | sed 's@/lib/ld-linux.so.2@/tools&@g' \\
    > \`dirname \$(gcc -print-libgcc-file-name)\`/specs"

    cmd "GCC_FIXED=\`dirname \$(gcc -print-libgcc-file-name)\`/include-fixed"
    cmd "find \${GCC_FIXED}/* -maxdepth 0 -xtype d -exec rm -rvf '{}' \;"
    cmd "rm -vf \`grep -l \"DO NOT EDIT THIS FILE\" \${GCC_FIXED}/*\`"
    cmd "unset GCC_FIXED"
    cmd "echo 'main(){}' > dummy.c"
    cmd "cc dummy.c"
    cmd "readelf -l a.out | grep ': /tools'"
    cmd "rm -v dummy.c a.out"
    place_marker "tools-adjust"
fi

if ! marker_exists "tools-tcl" ; then
    download_pkg ${TCL_PKG}
    unpack_pkg ${TCL_PKG}
    cmd "cd ${PKG_WORKDIR}/unix"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd 'chmod -v u+w /tools/lib/libtcl8.5.so'
    cmd "make install-private-headers"
    cmd "ln -sv tclsh8.5 /tools/bin/tclsh"
    cmd "cd ../.."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-tcl"
fi

if ! marker_exists "tools-expect" ; then
    download_pkg ${EXPECT_PKG}
    unpack_pkg ${EXPECT_PKG}
    download_patches ${EXPECT_PATCH0} ${EXPECT_PATCH1}
    cmd "cd ${PKG_WORKDIR}"
    cmd "patch -Np1 -i ../${PATCH_FILES[0]}"
    cmd "patch -Np1 -i ../${PATCH_FILES[1]}"
    cmd "cp configure{,.orig}"
    cmd "sed 's:/usr/local/bin:/bin:' configure.orig > configure"
    cmd "./configure --prefix=/tools --with-tcl=/tools/lib \\
    --with-tclinclude=/tools/include --with-x=no"
    cmd "make"
    cmd "make SCRIPTS=\"\" install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-expect"
fi

if ! marker_exists "tools-dejagnu" ; then
    download_pkg ${DEJAGNU_PKG}
    unpack_pkg ${DEJAGNU_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-dejagnu"
fi

if ! marker_exists "tools-gcc-pass2" ; then
    [[ -e gcc-build ]] && rm -rf gcc-build
    unpack_pkg ${GCC_PKG}
    download_patches ${GCC_PATCH0}
    cmd "cd ${PKG_WORKDIR}"
    cmd "cp -v gcc/Makefile.in{,.orig}"
    cmd "sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in"
    cmd "cp -v gcc/Makefile.in{,.tmp}"
    cmd "sed 's/^XCFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in.tmp \\
    > gcc/Makefile.in"
    cmd "for file in \$(find gcc/config -name linux64.h -o -name linux.h)
do
  cp -uv \$file{,.orig}
  sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \\
  -e 's@/usr@/tools@g' \$file.orig > \$file
  echo \"
#undef STANDARD_INCLUDE_DIR
#define STANDARD_INCLUDE_DIR 0\" >> \$file
  touch \$file.orig
done"
    get_pkg_file ${MPFR_PKG}
    cmd "tar xvf ../${PKG_FILE}"
    cmd "mv mpfr-2.3.2 mpfr"
    get_pkg_file ${GMP_PKG}
    cmd "tar xvf ../${PKG_FILE}"
    cmd "mv gmp-4.2.4 gmp"
    cmd "mkdir -v ../gcc-build"
    cmd "cd ../gcc-build"
    cmd "../gcc-4.3.2/configure --prefix=/tools \\
    --with-local-prefix=/tools --enable-clocale=gnu \\
    --enable-shared --enable-threads=posix \\
    --enable-__cxa_atexit --enable-languages=c,c++ \\
    --disable-libstdcxx-pch --disable-bootstrap"
    cmd "make"
    cmd "make install"
    cmd "echo 'main(){}' > dummy.c"
    cmd "cc dummy.c"
    cmd "readelf -l a.out | grep ': /tools'"
    cmd "rm -v dummy.c a.out"
    cmd "cd .."
    # cmd "rm -rf ${PKG_WORKDIR} gcc-build"
    place_marker "TMP-tools-gcc-pass2-ck-orig-files"
    place_marker "tools-gcc-pass2"
fi

if ! marker_exists "tools-binutils-pass2" ; then
    unpack_pkg ${BINUTILS_PKG}
    cmd "cd ${PKG_WORKDIR}"
    get_patch_files ${BINUTILS_PATCH0}
    cmd "patch -Np1 -i ../${PATCH_FILES[0]}"
    [[ -e ../binutils-build ]] && rm -rf ../binutils-build
    cmd "mkdir -v ../binutils-build"
    cmd "cd ../binutils-build"
    cmd "../binutils-2.18/configure --prefix=/tools \\
    --disable-nls --with-lib-path=/tools/lib"
    cmd "make"
    cmd "make install"
    cmd "make -C ld clean"
    cmd "make -C ld LIB_PATH=/usr/lib:/lib"
    cmd "cp -v ld/ld-new /tools/bin"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR} binutils-build"
    place_marker "tools-binutils-pass2"
fi

if ! marker_exists "tools-ncurses" ; then
    download_pkg ${NCURSES_PKG}
    unpack_pkg ${NCURSES_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools --with-shared \\
    --without-debug --without-ada --enable-overwrite"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-ncurses"
fi

if ! marker_exists "tools-bash" ; then
    download_pkg ${BASH_PKG}
    unpack_pkg ${BASH_PKG}
    download_patches ${BASH_PATCH0}
    cmd "cd ${PKG_WORKDIR}"
    cmd "patch -Np1 -i ../${PATCH_FILES[0]}"
    cmd "./configure --prefix=/tools --without-bash-malloc \\
    ac_cv_func_working_mktime=yes"
    cmd "make"
    cmd "make install"
    cmd "ln -vs bash /tools/bin/sh"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-bash"
fi

if ! marker_exists "tools-bzip2" ; then
    download_pkg ${BZIP2_PKG}
    unpack_pkg ${BZIP2_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "make"
    cmd "make PREFIX=/tools install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-bzip2"
fi

if ! marker_exists "tools-coreutils" ; then
    download_pkg ${COREUTILS_PKG}
    unpack_pkg ${COREUTILS_PKG}
    download_patches ${COREUTILS_PATCH1}
    cmd "cd ${PKG_WORKDIR}"
    cmd "patch -Np1 -i ../${PATCH_FILES[0]}"
    cmd "./configure --prefix=/tools --enable-install-program=hostname"
    cmd "make"
    cmd "make install"
    cmd "cp -v src/su /tools/bin/su-tools"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-coreutils"
fi

if ! marker_exists "tools-diffutils" ; then
    download_pkg ${DIFFUTILS_PKG}
    unpack_pkg ${DIFFUTILS_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-diffutils"
fi

if ! marker_exists "tools-e2fsprogs" ; then
    download_pkg ${E2FSPROGS_PKG}
    unpack_pkg ${E2FSPROGS_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "mkdir -v build"
    cmd "cd build"
    cmd "../configure --prefix=/tools"
    cmd "make"
    cmd "make install-libs"
    cmd 'chmod -v u+w /tools/lib/{libblkid,libcom_err,libe2p,libext2fs,libss,libuuid}.a'
    cmd "cd ../.."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-e2fsprogs"
fi

if ! marker_exists "tools-findutils" ; then
    download_pkg ${FINDUTILS_PKG}
    unpack_pkg ${FINDUTILS_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-findutils"
fi

if ! marker_exists "tools-gawk" ; then
    download_pkg ${GAWK_PKG}
    unpack_pkg ${GAWK_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools ac_cv_func_working_mktime=yes"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-gawk"
fi

if ! marker_exists "tools-gettext" ; then
    download_pkg ${GETTEXT_PKG}
    unpack_pkg ${GETTEXT_PKG}
    cmd "cd ${PKG_WORKDIR}/gettext-tools"
    cmd "./configure --prefix=/tools --disable-shared"
    cmd "make -C gnulib-lib"
    cmd "make -C src msgfmt"
    cmd "cp -v src/msgfmt /tools/bin"
    cmd "cd ../.."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-gettext"
fi

if ! marker_exists "tools-grep" ; then
    download_pkg ${GREP_PKG}
    unpack_pkg ${GREP_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools \\
    --disable-perl-regexp \\
    --without-included-regex"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-grep"
fi

if ! marker_exists "tools-gzip" ; then
    download_pkg ${GZIP_PKG}
    unpack_pkg ${GZIP_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "for file in gzip.c lib/utimens.{c,h} ; do \\
    cp -v \$file{,.orig}
    sed 's/futimens/gl_&/' \$file.orig > \$file
done"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    # cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "TMP-tools-gzip-ck-orig-files"
    place_marker "tools-gzip"
fi

if ! marker_exists "tools-m4" ; then
    download_pkg ${M4_PKG}
    unpack_pkg ${M4_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-m4"
fi

if ! marker_exists "tools-make" ; then
    download_pkg ${MAKE_PKG}
    unpack_pkg ${MAKE_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-make"
fi

if ! marker_exists "tools-patch" ; then
    download_pkg ${PATCH_PKG}
    unpack_pkg ${PATCH_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-patch"
fi

if ! marker_exists "tools-perl" ; then
    download_pkg ${PERL_PKG}
    unpack_pkg ${PERL_PKG}
    download_patches ${PERL_PATCH0}
    cmd "cd ${PKG_WORKDIR}"
    cmd "patch -Np1 -i ../${PATCH_FILES[0]}"
    cmd "sh Configure -des -Dprefix=/tools \\
    -Dstatic_ext='Data/Dumper Fcntl IO POSIX'"
    cmd "make perl utilities ext/Errno/pm_to_blib"
    cmd "cp -v perl pod/pod2man /tools/bin"
    cmd "mkdir -pv /tools/lib/perl5/5.10.0"
    cmd "cp -Rv lib/* /tools/lib/perl5/5.10.0"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-perl"
fi

if ! marker_exists "tools-sed" ; then
    download_pkg ${SED_PKG}
    unpack_pkg ${SED_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-sed"
fi

if ! marker_exists "tools-tar" ; then
    download_pkg ${TAR_PKG}
    unpack_pkg ${TAR_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-tar"
fi

if ! marker_exists "tools-texinfo" ; then
    download_pkg ${TEXINFO_PKG}
    unpack_pkg ${TEXINFO_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd "make"
    cmd "make install"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-texinfo"
fi

if ! marker_exists "tools-util-linux" ; then
    download_pkg ${UTIL_LINUX_PKG}
    unpack_pkg ${UTIL_LINUX_PKG}
    cmd "cd ${PKG_WORKDIR}"
    cmd "./configure --prefix=/tools"
    cmd 'make BLKID_LIBS="-lblkid -luuid" -C mount mount umount'
    cmd "make -C text-utils more"
    cmd "cp -v mount/{,u}mount text-utils/more /tools/bin"
    cmd "cd .."
    cmd "rm -rf ${PKG_WORKDIR}"
    place_marker "tools-util-linux"
fi

remove_pid "pris-rebuild-b"

place_marker "TMP-ck-exit-written-to-log"
cmd "exit"

exit 0
